rename quilt to patches, adapt build script, remove old patches

diff --git a/build-ptexlive-binaries b/build-ptexlive-binaries
--- a/build-ptexlive-binaries
+++ b/build-ptexlive-binaries
@@ -3,6 +3,8 @@
 #
 # Changelog
 # 2012-11-07 update from HK fro pmpost and fixes for current svn sources
+# 2013-01-06 move patches to quilt, include reautoconf patch so that
+#            call to reautoconf is not necessary anymore
 #
 # on Debian, needs:
 # libx11-dev, libxaw7-dev, libfontconfig1-dev, bison, flex
@@ -15,11 +17,13 @@ set -e
 DO_APPLE=0
 DO_NOX=0
 DO_NOPREP=0
+DO_MAINT=0
 while [ "${1+defined}" ]; do
   case "$1" in
   "--macosx") DO_APPLE=1;;
   "--nox") DO_NOX=1;;
   "--noprep") DO_NOPREP=1;;
+  "--maintainer") DO_MAINT=1;;
   *) echo "unsupported argument $1, exit."; exit 1 ;;
   esac
   shift
@@ -89,14 +93,6 @@ EOF
   sleep 3
 fi
 
-sedwrite(){
-  echo "rewriting `basename $1` by \"$2\""
-  if [ ! -f "$1" ]; then 
-    echo -e "'$1' does not exist"; exit 1
-  fi
-  perl -pi -e  "$2" "$1" || exit 1
-}
-
 if [ $DO_NOPREP = 0 ] ; then
   # get current TL sources
   if [ "$NORSYNC" != "1" ] ; then
@@ -107,25 +103,47 @@ if [ $DO_NOPREP = 0 ] ; then
   cd $SOURCE
 
   # pxdvi
-  echo "preparing pxdvi"
+  echo "creating pxdvi folder"
   cp -pR texk/xdvik texk/pxdvik
-  echo "patching pxdvi patches"
-  echo "patching with xdvik-20121204-tl12.diff"
-  $PATCH -d texk/pxdvik -p1 < $PATCHES/xdvik-20121204-tl12.diff
-  echo "patching with pxdvik-20111126-density.diff"
-  $PATCH -d texk/pxdvik -p1 < $PATCHES/pxdvik-20111126-density.diff
-  echo "patching with pxdvik-20111212-uptex.diff"
-  $PATCH -d texk/pxdvik -p1 < $PATCHES/pxdvik-20111212-uptex.diff 
-  sedwrite libs/freetype2/freetype-2.4.*/modules.cfg 's/# (AUX_MODULES \+= otvalid)/\1/'
-  sedwrite m4/kpse-pkgs.m4 "s/xdvik/xdvik\npxdvik/"
 
-  # pmpost
-  echo "patching pmpost"
-  $PATCH -d texk -p0 < $PATCHES/pmpost-20121204-tl12.diff
-  $PATCH -d texk -p0 < $PATCHES/pmpost-svg-20120119-tl11.diff 
 
-  echo "running reautoconf"
-  ./reautoconf
+  echo "applying patches"
+  if which quilt >/dev/null ; then
+    if  $DO_MAINT = 1 ] ; then
+      export QUILT_PATCHES="$PATCHES/patches"
+      while [ $(quilt next) ne "reautoconf-stuff" ] ; do
+        quilt push
+      done
+      tempdir=$(mktemp -d)
+      echo "Copying source for reautoconf diff"
+      cp -a "$SOURCE" $tempdir/source-reautoconf
+      cd $tempdir/source-reautoconf
+      echo "Running reautoconf"
+      TL_AUTOMAKE=automake-1.13 TL_ACLOCAL=aclocal-1.13 ./reautoconf
+      echo "Updating reautoconf-stuff patch"
+      diff -urN -x 'autom4te.cache' "$SOURCE" $tempdir/source-reautoconf > $PATCHES/patches/reautoconf-stuff
+      cd "$SOURCE"
+      rm -rf $tempdir
+      echo "Pushing new changes ... please verify it worked!"
+      quilt push
+      exit $?
+      # update the reautoconf patch!
+    else
+      QUILT_PATCHES="$PATCHES/patches" quilt push -a
+    fi
+  else
+    if [ $DO_MAINT = 1 ] ; then
+      echo "Cannot work without quilt in maintainer mode, exiting here."
+      echo "Please clean up yourself."
+      exit 1
+    fi
+    cat "$PATCHES/patches/series" | while read p r ; do
+      $PATCH $r $p
+    done
+  fi
+
+  #echo "running reautoconf"
+  #TL_AUTOMAKE=automake-1.13 TL_ACLOCAL=aclocal-1.13 ./reautoconf
 fi	# of $DO_NOPREP = 0
 
 
